services:
  # DB
  mongo:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mongodb/mongodb-community-server:8.0.11-ubi9
    container_name: mongo
    restart: always
    networks:
      - aigame
    ports:
      - '27017:27017'
    environment:
      - TZ=Asia/Shanghai
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo:/data/db  # 持久化数据目录
      - /etc/localtime:/etc/localtime:ro
      - ./mongodb.key:/etc/mongo/mongodb.key:ro
    command:
      - "mongod"
      - "--replSet"
      - "rs0"
      - "--bind_ip_all"
      - "--keyFile"
      - "/etc/mongo/mongodb.key"
  redis:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:8.0.3
    container_name: redis
    restart: always
    networks:
      - aigame
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password  # Redis密码（根据镜像是否支持该环境变量调整，部分镜像需通过配置文件设置）
      - TZ=Asia/Shanghai
    volumes:
      - ./data/redis:/data  # 持久化数据目录
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/timezone:ro
    command: redis-server --requirepass password  # 启动时设置密码（若环境变量不生效时使用）
  aigame-minio:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/minio/minio:latest
    container_name: aigame-minio
    restart: always
    networks:
      - aigame
    ports: # comment out if you do not need to expose the port (in production environment, you should not expose the port)
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - TZ=Asia/Shanghai
    volumes:
      - ./data/minio:/data
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/timezone:ro
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  aigame: