# Generated by Django 5.0.7 on 2024-07-16 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='电子邮件地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='用户是否活跃'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='用户是否是超级用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='用户全名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='队伍名字')),
                ('description', models.TextField(blank=True, verbose_name='队伍介绍')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='队伍头像')),
                ('captain', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_team', to='user.user', verbose_name='队长')),
                ('members', models.ManyToManyField(related_name='teams', to='user.user', verbose_name='队伍成员')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
