# Generated by Django 5.0.7 on 2024-07-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
