# Generated by Django 5.0.7 on 2024-07-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='队伍名字')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='队伍头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='队伍是否激活')),
                ('captain', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='user.user', verbose_name='队长')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='user.team', verbose_name='所在队伍'),
        ),
    ]
