# Generated by Django 5.0.7 on 2024-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_team_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='邀请码'),
        ),
    ]
