# Generated by Django 5.0.7 on 2024-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_team_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('INACTIVE', '未激活'), ('PENDING_REVIEW', '待审核'), ('ACTIVE', '已激活')], default='INACTIVE', max_length=20, verbose_name='队伍状态'),
        ),
    ]
